version: "3"
services: 
  core:
    build: .
    image: aria-core:latest
    entrypoint: [ "python", "run.py" ]
    working_dir: /usr/src/aria-core
    volumes:
    - ./:/usr/src/aria-core
    restart: always
  core-redis:
    image: redis
